# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170628_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='Image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
