# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_productimages_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialsproduct',
            old_name='MaterialsID',
            new_name='Materials',
        ),
        migrations.RenameField(
            model_name='materialsproduct',
            old_name='ProductID',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='CustomerID',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='OrderID',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='ProductID',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='productcontactperson',
            old_name='ProductID',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='ProductID',
            new_name='Product',
        ),
    ]
