# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170629_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='Materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Materials'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderTotalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Categories'),
        ),
    ]
