# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170629_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='product',
            name='Address',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=191),
        ),
    ]
