# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170629_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
    ]
