# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170630_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
    ]
