# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170630_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description_eng',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
